# Generated by Django 4.1.7 on 2023-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenermodel',
            name='shortened_url',
        ),
        migrations.AddField(
            model_name='shortenermodel',
            name='encoded',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shortenermodel',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortenermodel',
            name='source_url',
            field=models.URLField(unique=True),
        ),
    ]
