# Generated by Django 4.1.7 on 2023-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_shortenermodel_shortened_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenermodel',
            name='encoded',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
