# Generated by Django 4.1.7 on 2023-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shortenermodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenermodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
